### ISSUE TITLE
CDCACM::availabe() blocks

### ISSUE THREAD

**Issue by bjc** [bjc/ArduinoCore-GD32#5]
Upstream issue: https://github.com/CommunityGD32Cores/ArduinoCore-GD32/issues/56

**Comment by algernon** [comment]
Hey!

A bit of an update on the issue, and why `.available()` is pretty much essential for Kaleidoscope: the protocol between the keyboard and the host implemented by Kaleidoscope is a bi-directional protocol, and the most often used method is a request-response one, initiated by the host.

To be able to handle that, we need to be able to tell whether there's data available via Serial. We can't just use a blocking read, because then the rest of the keyboard functionality would be lost until the host sends data. The issue is further complicated by the protocol being rather loose, and there are often scenarios where the firmware doesn't know how much data to read or expect, because data can end abruptly, and still be valid.

For example, to reprogram the keys on a keyboard, the command to send over serial is `keymap.map <code> <code>...`, where `<code>` is the keycode for a particular key. Any number of codes can be sent, and then the first N keys will be remapped. It's also common to just send the raw command, `keymap.map`, without arguments, to query the keymap. Both of these things require Kaleidoscope to know whether there's data available.

The implementation heavily relies on this. We could, in theory, come up with a protocol that doesn't, but that'd be a _huge_ breaking change, and quite an undertaking.
